.github/workflows/build_paper.yml
Warning: `Unexpected input(s) 'allowUpdates'`. I believe this parameter has been deprecated.
=> Fix warning in workflow: remove 'allowUpdates'

.gitignore
Adds ignore rules to ensure that paper.pdf and other generated files aren't commited by accident. 
Note that I couldn't execute make, as the build is currently broken on the master branch.
=> Add ignore rules for generated files

.gitignore
Use the [tex.gitignore](https://github.com/github/gitignore/blob/master/TeX.gitignore) collated ignore list which ignores all of latex's many byproducts.
I ran into the current `gitignore` not ignoring `minted` generated files (`*.pyg`).
=> add all gitignores from github tex.gitignore

paper.tex, tools/MLIRLexer.py
This pull request adds a custom pygments formatter that allows us to syntax-highlight MLIR.
It currently supports:
- Lexing a simple subset of MLIR
- Highlighting only the OPs
- Adding \circled marks into the listing
[
](url)
=> Add an example for how to format a listing

paper.tex
The underlined text seemed to disappear in non-draft mode previously.
=> Non-draft mode: do not omit text that is referred to in a comment

paper.tex
Not sure why this exists. It seemed to result in comments being replaced with the text `emptystring`. The paper seems to compile fine without it.
=> non-draft mode: do not insert "emptystring" in place of comments

paper.tex
- The bib file is called 'references' and non 'bibfile', thus rename to
'references'.
- For some reason the import of the bib file was commented.
=> Fix include for bib file

paper.tex, tools/MLIRLexer.py
This PR adds support for syntax highlighting more IR styles, in particular xDSL style. As I did not follow MLIR's guidelines very closely but rather implemented syntax highlighting for the code i need in my thesis, this might support some ill-formatted IRs. However, I still wanted to make this available for more people.
I feel that we should probably refactor this majorly in order to make all the regex readable and understand what they are supposed to match on.
=> FEAT: more functionality for highlighting MLIR/xDSL Code

paper.tex
Without this, \autoref{lst:affine} does not write Listing 1 for me. Instead it only writes 1. I don't know why it works in the Appendix though without this.
=> Support Listing in autoref

shell.nix
This PR aims to add native development and building support for NixOS.
It currently adds a `shell.nix` file containing all dependencies (except for texlive). 
If you wish to use pure nix-shells, you'll need to un-comment the `my-texlive` dependency, it should contain all required texlive packages. If you do this, you can successfully build drafts and papers using `nix-shell --pure --run "make all"`.
=> Add nixos support

.github/workflows/build_paper_old.yml, paper.tex, tex/setup.tex, tools/create-video.py
The minted 2.7 release changed its behaviour to not allow for custom command line options, which broke our custom lexer definitions. Here is a similar bug reported: https://github.com/gpoore/minted/issues/360.
This commit adds a new minted option that allows custom lexers to work with newer texlive distributions. We also enhance our CI to check that the paper builds with old and new textlive distributions.
=> Make minted custom lexers work for old and new Texlive Releases

.github/workflows/build_paper.yml, .github/workflows/build_paper_old.yml, Makefile, README.md, draft.tex, paper.tex, submission.tex
When editing a paper we want to see the version with comments. In VSCode, it is easy to look at the PDF that is created from the main .tex file, paper.tex in our case. Hence, we make this version the one with comments.
For submission, we always have submission.pdf that will give us a file without comments and without extended document size.
=> Print comments in paper.pdf and create submission.pdf without comments

paper.tex, tex/setup.tex
This PR:
- Factors out the tikz node style to avoid repetition
- Fixes #41 (there is no typographic guarantee regarding the total height of letters wrt cap height and/or ascenders in a character, so the numbers are a result of experimenting with what accommodates letters with ascenders and descenders)
A lot of this is based on the `\strut` suggestion [here][1].
[1]: https://tex.stackexchange.com/a/199056/78375
=> Fix circled command

Makefile
This PR adds minor improvements (mostly DRY-specific) to the `Makefile`:
- Define the TeX filenames once and use their variables everywhere else needed
- Declare all phony targets
=> Add minor `Makefile` improvements

Makefile, paper.tex, tex/setup.tex
This PR:
- Adds `Makefile` check (by invoking `make refcheck`) for all labelled elements that are not referenced in the text
- Adds explanatory text on this within the template's writing and style guidelines
PS: I know `textidote` offers this but this is available on every compilation by just parsing the log
=> Adds `Makefile` check for all labelled elements are not referenced in text

paper.tex
This PR:
- Adds `hyphenat` package
- Gives example of how to customize hyphenation in the writing guidelines, as it is too common to have CS names that have no hyphenation rules in the default LaTeX Texlive distro.
=> Add hyphenation package and explanation

paper.tex
This PR:
- Adds a macro detection for minted v3 (included in latex TeXLive distros)
- This is also towards fixing #59 
This was the suggested way to do this by the `minted` devs as discussed in [here](https://github.com/gpoore/minted/issues/432#issuecomment-2628553173)
@alexarice can you please try this locally? It works for me using the latest Latex docker from #59 and also with my local TexLive which still uses `minted` v2
=> Detect `minted` version 3

.github/workflows/build_paper.yml, README.md
Let's revert #57 
~Stacked on #61~
=> Update TeXLive to latest monthly release

paper.tex
This is useful since we don't retain logs in the CI but the assets (i.e., the compiled pdfs are kept around).
=> Add minted version info in document

Makefile, tools/generate_lexers_json.py
This PR modifies the `generate_lexers_json` script to preserve configuration in the .latexminted_config file outside of the custom_lexers option, when refreshing the SHAs.
=> Preserve customized latexminted configuration when refreshing lexer SHAs
